const STOCK_TV_MAP = {
  AAPL: "NASDAQ:AAPL",
  MSFT: "NASDAQ:MSFT",
  GOOGL: "NASDAQ:GOOGL",
  AMZN: "NASDAQ:AMZN",
  META: "NASDAQ:META",
  NVDA: "NASDAQ:NVDA",
  TSLA: "NASDAQ:TSLA",
  NFLX: "NASDAQ:NFLX",
  AMD: "NASDAQ:AMD",
  INTC: "NASDAQ:INTC",
  ORCL: "NYSE:ORCL",
  CRM: "NYSE:CRM",
  ADBE: "NASDAQ:ADBE",
  IBM: "NYSE:IBM",
  CSCO: "NASDAQ:CSCO",
  QCOM: "NASDAQ:QCOM",
  UBER: "NYSE:UBER",
  ABNB: "NASDAQ:ABNB",
  SPOT: "NYSE:SPOT",
  PYPL: "NASDAQ:PYPL",
  V: "NYSE:V",
  MA: "NYSE:MA",
  JPM: "NYSE:JPM",
  BAC: "NYSE:BAC",
  WMT: "NYSE:WMT",
  COST: "NASDAQ:COST",
  HD: "NYSE:HD",
  KO: "NYSE:KO",
  PEP: "NASDAQ:PEP",
  MCD: "NYSE:MCD",
  NKE: "NYSE:NKE",
  SBUX: "NASDAQ:SBUX",
  DIS: "NYSE:DIS",
  BA: "NYSE:BA",
  F: "NYSE:F",
  GM: "NYSE:GM",
  XOM: "NYSE:XOM",
  CVX: "NYSE:CVX",
  PFE: "NYSE:PFE",
  JNJ: "NYSE:JNJ",
  T: "NYSE:T",
  VZ: "NYSE:VZ",
};

const CRYPTO_TV_MAP = {
  BTC: "BINANCE:BTCUSDT",
  ETH: "BINANCE:ETHUSDT",
  SOL: "BINANCE:SOLUSDT",
  XRP: "BINANCE:XRPUSDT",
  DOGE: "BINANCE:DOGEUSDT",
  ADA: "BINANCE:ADAUSDT",
  BNB: "BINANCE:BNBUSDT",
  MATIC: "BINANCE:MATICUSDT",
  DOT: "BINANCE:DOTUSDT",
  LTC: "BINANCE:LTCUSDT",
};

export function getTradingViewSymbol(ticker, type) {
  const upper = (ticker || "").toUpperCase();
  if (type === "crypto") {
    return CRYPTO_TV_MAP[upper] || `BINANCE:${upper}USDT`;
  }
  return STOCK_TV_MAP[upper] || `NASDAQ:${upper}`;
}
